/*============================================================================
Filename : touch.c
Project : QTouch Modular Library
Purpose : Provides Initialization, Processing and ISR handler of touch library,
          Simple API functions to get/set the key touch parameters from/to the
          touch library data structures

This file is part of QTouch Modular Library Release 7.5 application.

Important Note: Do not edit this file manually.
                Use QTouch Configurator within Atmel Start to apply any
                modifications to this file.

Usage License: Refer license.h file for license information
Support: Visit http://www.microchip.com/support/hottopics.aspx
               to create MySupport case.

------------------------------------------------------------------------------
Copyright (c) 2021 Microchip. All rights reserved.
------------------------------------------------------------------------------
============================================================================*/
/*
	Change note:
	v23-20210413: low power mode support
		remove `qtlib_time_elapsed_since_update`, and involved `measurement_period_(active/idle)_store
	
*/

#ifndef TOUCH_C
#define TOUCH_C

#ifdef __XC32__
#warning "The library is not tested for XC32 compiler, use ARM-GCC compiler instead"
#endif

/*----------------------------------------------------------------------------
 *     include files
 *----------------------------------------------------------------------------*/

#include "touch.h"
#include "license.h"
#ifdef USE_WDT
#include "wdt.h"
#endif
#include "port.h"

#include "datastreamer.h"

#if DEF_PTC_CAL_OPTION != CAL_AUTO_TUNE_NONE
#error "Autotune feature is NOT supported by this acquisition library. Enable Autotune featuers in START."
#endif

#ifdef DEF_TOUCH_DATA_STREAMER_ENABLE
#if DEF_PTC_CAL_OPTION != CAL_AUTO_TUNE_NONE
#warning                                                                                                               \
    "Automatic charge time option is enabled without enabling datastreamer. So, automatic tuning of charge time option is disabled."
#define DEF_PTC_CAL_OPTION CAL_AUTO_TUNE_NONE
#endif
#endif

/*----------------------------------------------------------------------------
 *   prototypes
 *----------------------------------------------------------------------------*/

/*! \brief configure the ptc port pins to Input
 */
/* static */void touch_ptc_pin_config(void);

/*! \brief configure keys, wheels and sliders.
 */
static touch_ret_t touch_sensors_config(void);

/*! \brief Touch measure complete callback function example prototype.
 */
static void qtm_measure_complete_callback(void);

/*! \brief Touch Error callback function prototype.
 */
static void qtm_error_callback(uint8_t error);

#if (DEF_TOUCH_LOWPOWER_ENABLE == 1u)
/* low power processing function */
static void touch_process_lowpower(void);
void touch_set_scan_rate(void);

/* low power touch detection callback */
static void touch_measure_wcomp_match(void);
/* Cancel low-power measurement */
static void touch_cancel_autoscan(void);
static void touch_enable_lowpower_measurement(void);
static void touch_disable_lowpower_measurement(void);

#endif

/*----------------------------------------------------------------------------
 *     Global Variables
 *----------------------------------------------------------------------------*/

/* USE_MPTT_WRAPPER */
enum _QLIB_STATE {
	// lib suspend, not working or in other mode like ADC
	QTLIB_STATE_SUSPEND = 0,
	// lib at sleep mode
	QTLIB_STATE_SLEEP,
	// lib in normal mode but idle
	QTLIB_STATE_IDLE,
	// lib in normal mode and in measurement
	QTLIB_STATE_ACTIVE,
	// lib finished measurement
	QTLIB_STATE_COMPLETE,
	QTLIB_STATE_LOW_POWER_SCANNING,
};
/* set to non zero suspend the sampling */
uint8_t qlib_touch_flag = QTLIB_STATE_SUSPEND;

/* lib at low power scanning mode */
uint8_t qlib_lowpower_flag = 0;

/* Flag to indicate time for touch measurement */
// volatile uint8_t time_to_measure_touch_flag = 0;

/* postporcess request flag */
volatile uint8_t touch_postprocess_request = 0;

/* Measurement Done Touch Flag  */
volatile uint8_t measurement_done_touch = 0;

/* Error Handling */
uint8_t module_error_code = 0;

/* Low-power measurement variables, store how long last touch elapsed, unit: ms 
	initialized as infinite value
*/
uint16_t time_since_touch = (uint16_t)-1;
/*	MPTT required change:
	set 2 varibles for the measurement period: active and idle by `measurement_period_store`
	`measurement_period_active_store`: active measurement period
	`measurement_period_idle_store`: idle measurement period(for low power mode)
	*/
uint16_t measurement_period_store = DEF_TOUCH_MEASUREMENT_PERIOD_MS;
/*
	MPTT required change:
	Active Acquisition Interval
	Range: [0~255], unit 1ms
	0: suspend
	1 ~ 254: actual value with 1ms unit
	255: free run
	*/
uint8_t measurement_period_active_store = DEF_TOUCH_MEASUREMENT_PERIOD_MS;

/*	
	MPTT required change:
	Idle Acquisition Interval
	0: disable sleep mode	
	1 ~ 255: actual value with 1ms unit
*/
uint8_t measurement_period_idle_store = DEF_TOUCH_MEASUREMENT_IDLE_PERIOD_MS;

/*
	The Active to Idle Timeout is specified in 200 ms increments, where 0 means don't enter into idle automatically.
	Range: 0 (1 cycle), 1 to 4095, unit 200ms
*/
uint8_t measurement_active_to_idle = DEF_TOUCH_ACTIVE_IDLE_TIMEOUT;

/* Acquisition module internal data - Size to largest acquisition set */
uint16_t touch_acq_signals_raw[DEF_NUM_CHANNELS];

/* Acquisition set 1 - General settings */
qtm_acq_node_group_config_t ptc_qtlib_acq_gen1
    = {DEF_NUM_CHANNELS, DEF_SENSOR_TYPE, DEF_PTC_CAL_AUTO_TUNE, DEF_SEL_FREQ_INIT};

/* Node status, signal, calibration values */
qtm_acq_node_data_t ptc_qtlib_node_stat1[DEF_NUM_CHANNELS];

/* Node configurations */
qtm_acq_t321x_node_config_t ptc_seq_node_cfg1[DEF_NUM_CHANNELS]
    = {NODE_0_PARAMS, NODE_1_PARAMS, NODE_2_PARAMS, NODE_3_PARAMS};

/* Container */
qtm_acquisition_control_t qtlib_acq_set1 = {&ptc_qtlib_acq_gen1, &ptc_seq_node_cfg1[0], &ptc_qtlib_node_stat1[0]};

/* Low-power autoscan related parameters */
qtm_auto_scan_config_t auto_scan_setup
    = {&qtlib_acq_set1, QTM_AUTOSCAN_NODE, QTM_AUTOSCAN_THRESHOLD, /*QTM_AUTOSCAN_TRIGGER_PERIOD*/0};

/**********************************************************/
/*********** Frequency Hop Module **********************/
/**********************************************************/

/* Buffer used with various noise filtering functions */
uint16_t noise_filter_buffer[DEF_NUM_SENSORS * NUM_FREQ_STEPS];
uint8_t  freq_hop_delay_selection[NUM_FREQ_STEPS] = {DEF_MEDIAN_FILTER_FREQUENCIES};

/* Configuration */
qtm_freq_hop_config_t qtm_freq_hop_config1 = {
    DEF_NUM_CHANNELS,
    NUM_FREQ_STEPS,
    &ptc_qtlib_acq_gen1.freq_option_select,
    &freq_hop_delay_selection[0],
};

/* Data */
qtm_freq_hop_data_t qtm_freq_hop_data1 = {0, 0, &noise_filter_buffer[0], &ptc_qtlib_node_stat1[0]};

/* Container */
qtm_freq_hop_control_t qtm_freq_hop_control1 = {&qtm_freq_hop_data1, &qtm_freq_hop_config1};

/**********************************************************/
/*********************** Keys Module **********************/
/**********************************************************/

/* Keys set 1 - General settings */
qtm_touch_key_group_config_t qtlib_key_grp_config_set1 = {DEF_NUM_SENSORS,
                                                          DEF_TOUCH_DET_INT,
                                                          DEF_MAX_ON_DURATION,
                                                          DEF_ANTI_TCH_DET_INT,
                                                          DEF_ANTI_TCH_RECAL_THRSHLD,
                                                          DEF_TCH_DRIFT_RATE,
                                                          DEF_ANTI_TCH_DRIFT_RATE,
                                                          DEF_DRIFT_HOLD_TIME,
                                                          DEF_REBURST_MODE};

qtm_touch_key_group_data_t qtlib_key_grp_data_set1;

/* Key data */
qtm_touch_key_data_t qtlib_key_data_set1[DEF_NUM_SENSORS];

/* Key Configurations */
qtm_touch_key_config_t qtlib_key_configs_set1[DEF_NUM_SENSORS]
    = {KEY_0_PARAMS, KEY_1_PARAMS, KEY_2_PARAMS, KEY_3_PARAMS};

/* Container */
qtm_touch_key_control_t qtlib_key_set1
    = {&qtlib_key_grp_data_set1, &qtlib_key_grp_config_set1, &qtlib_key_data_set1[0], &qtlib_key_configs_set1[0]};

#ifndef USE_MPTT_WRAPPER
#error "be careful to re-configure here since there isn't enabled PTC pin auto config"
/*static*/ void touch_ptc_pin_config(void)
{

	PORTC_set_pin_pull_mode(2, PORT_PULL_OFF);
	PORTC_pin_set_isc(2, PORT_ISC_INPUT_DISABLE_gc);

	PORTC_set_pin_pull_mode(3, PORT_PULL_OFF);
	PORTC_pin_set_isc(3, PORT_ISC_INPUT_DISABLE_gc);

	PORTC_set_pin_pull_mode(4, PORT_PULL_OFF);
	PORTC_pin_set_isc(4, PORT_ISC_INPUT_DISABLE_gc);

	PORTA_set_pin_pull_mode(6, PORT_PULL_OFF);
	PORTA_pin_set_isc(6, PORT_ISC_INPUT_DISABLE_gc);
}
#endif

/*============================================================================
static touch_ret_t touch_sensors_config(void)
------------------------------------------------------------------------------
Purpose: Initialization of touch key sensors
Input  : none
Output : none
Notes  :
============================================================================*/
/* Touch sensors config - assign nodes to buttons / wheels / sliders / surfaces / water level / etc */
static touch_ret_t touch_sensors_config(void)
{
	uint16_t    sensor_nodes;
	touch_ret_t touch_ret = TOUCH_SUCCESS;

	/* Init acquisition module */
	qtm_ptc_init_acquisition_module(&qtlib_acq_set1);

	/* Init pointers to DMA sequence memory */
	qtm_ptc_qtlib_assign_signal_memory(&touch_acq_signals_raw[0]);

	/* Initialize sensor nodes */
	for (sensor_nodes = 0u; sensor_nodes < DEF_NUM_CHANNELS; sensor_nodes++) {
		/* Enable each node for measurement and mark for calibration */
		qtm_enable_sensor_node(&qtlib_acq_set1, sensor_nodes);
		qtm_calibrate_sensor_node(&qtlib_acq_set1, sensor_nodes);
	}

	/* Enable sensor keys and assign nodes */
	for (sensor_nodes = 0u; sensor_nodes < DEF_NUM_CHANNELS; sensor_nodes++) {
		qtm_init_sensor_key(&qtlib_key_set1, sensor_nodes, &ptc_qtlib_node_stat1[sensor_nodes]);
	}

	return (touch_ret);
}

/*============================================================================
static void qtm_measure_complete_callback( void )
------------------------------------------------------------------------------
Purpose: this function is called after the completion of
         measurement cycle. This function sets the post processing request
         flag to trigger the post processing.
Input  : none
Output : none
Notes  :
============================================================================*/
static void qtm_measure_complete_callback(void)
{
	touch_postprocess_request = 1u;
}

/*============================================================================
static void qtm_error_callback(uint8_t error)
------------------------------------------------------------------------------
Purpose: this function is used to report error in the modules.
Input  : error code
Output : decoded module error code
Notes  :
Derived Module_error_codes:
    Acquisition module error =1
    post processing module1 error = 2
    post processing module2 error = 3
    ... and so on
============================================================================*/
static void qtm_error_callback(uint8_t error)
{
	module_error_code = error + 1u;
#ifdef USE_MPTT_WRAPPER
	// return done error that make the state machine continue running
	qlib_touch_flag = QTLIB_STATE_IDLE;
	
	measurement_done_touch = 2;
#endif
#ifdef DEF_TOUCH_DATA_STREAMER_ENABLE
	datastreamer_output();
#endif
}

/*============================================================================
void Timer_set_period(const uint8_t val, bool pit_en)
------------------------------------------------------------------------------
Purpose: This function sets the time interval on the RTC/Timer peripheral based
         on the user configuration, the RTC timer has been configured as 1 quarter ms unit
Input  : Time interval(ms), pit enable/disable
Output : none
Notes  :
============================================================================*/
void Timer_set_period(const uint16_t val, const bool pit)
{
	/* Disable Clock and PIT */

	while (RTC.STATUS & RTC_CTRLABUSY_bm)
		;                               /* wait for RTC synchronization */
	RTC.CTRLA &= ~(1u << RTC_RTCEN_bp); /* Clock disabled */

	if (!pit) {
		/* Disable PIT */
		while (RTC.PITSTATUS & RTC_CTRLBUSY_bm)
			;
		RTC.PITCTRLA &= ~(1u << RTC_PITEN_bp); /* PIT disabled */
	}
		
	if (val != 0) {
		while (RTC.STATUS & RTC_PERBUSY_bm)
			;          /* wait for RTC synchronization */
		if (val <= 0x3FFF)
			RTC.PER = (val & 0x3FFF) << 2; /* Set period register, RTC cycle use 1/quarter ms */
		else
			RTC.PER = 0xFFFF;
		RTC.INTCTRL |= (1 << RTC_OVF_bp);
	} else { /* if the value is zero, disable interrupt */
		RTC.INTCTRL &= ~(1 << RTC_OVF_bp);
	}

	while (RTC.STATUS & RTC_CNTBUSY_bm)
		;         /* wait for RTC synchronization */
	RTC.CNT = 0u; /* Clear count register */
	
	if (val && pit) {
		/* Enable Clock and PIT */
		while (RTC.PITSTATUS & RTC_CTRLBUSY_bm)
			;
		RTC.PITCTRLA |= 1 << RTC_PITEN_bp;	/* PIT enabled */
	}
	

	/* Enable Clock */
	while (RTC.STATUS & RTC_CTRLABUSY_bm)
		;                           /* wait for RTC synchronization */
	RTC.CTRLA |= 1 << RTC_RTCEN_bp; /* clock Enabled */
}

/*============================================================================
void touch_init(void)
------------------------------------------------------------------------------
Purpose: Initialization of touch library. PTC, timer, and
         datastreamer modules are initialized in this function.
Input  : none
Output : none
Notes  :
============================================================================*/
void touch_init(void)
{

	// USE_MPTT_WRAPPER changed
	/* Set match value for timer,
		Here we don't start the scanning automatically, if zero we suspend default */
	qlib_touch_flag = QTLIB_STATE_IDLE;
	Timer_set_period(measurement_period_store, false);
	
	/* configure the PTC pins for Input*/
	touch_ptc_pin_config();
#if DEF_TOUCH_LOWPOWER_ENABLE == 1u
	//touch_disable_lowpower_measurement();
#endif

	/* Configure touch sensors with Application specific settings */
	touch_sensors_config();

#ifdef DEF_TOUCH_DATA_STREAMER_ENABLE
	datastreamer_init();
#endif
}

/*============================================================================
uint8_t touch_process(void)
------------------------------------------------------------------------------
Purpose: Main processing function of touch library. This function initiates the
         acquisition, calls post processing after the acquistion complete and
         sets the flag for next measurement based on the sensor status.
Input  : none
Output : 1 busy, 0 idle
Notes  :
============================================================================*/
uint8_t touch_process(void)
{
	touch_ret_t touch_ret;
	
	/* USE_MPTT_WRAPPER */
	touch_set_scan_rate();
		
	/* check the qlib_touch_flag flag for Touch Acquisition */
	// if (time_to_measure_touch_flag == 1u) {
	if (qlib_touch_flag == QTLIB_STATE_ACTIVE) {
		/* Do the acquisition */
		touch_ret = qtm_ptc_start_measurement_seq(&qtlib_acq_set1, qtm_measure_complete_callback);

		/* if the Acquistion request was successful then clear the request flag */
		if (TOUCH_SUCCESS == touch_ret) {
			/* Clear the Measure request flag */
			// time_to_measure_touch_flag = 0u;
			qlib_touch_flag = QTLIB_STATE_IDLE;
		}
	}

	/* check the flag for node level post processing */
	if (touch_postprocess_request == 1u) {
		/* Reset the flags for node_level_post_processing */
		touch_postprocess_request = 0u;
		qlib_touch_flag = QTLIB_STATE_COMPLETE;

		/* Run Acquisition module level post processing*/
		touch_ret = qtm_acquisition_process();

		/* Check the return value */
		if (TOUCH_SUCCESS == touch_ret) {
			/* Returned with success: Start module level post processing */
			touch_ret = qtm_freq_hop(&qtm_freq_hop_control1);
			if (TOUCH_SUCCESS != touch_ret) {
				qtm_error_callback(1);
			}
			touch_ret = qtm_key_sensors_process(&qtlib_key_set1);
			if (TOUCH_SUCCESS != touch_ret) {
				qtm_error_callback(2);
			}
		} else {
			/* Acq module Eror Detected: Issue an Acq module common error code 0x80 */
			qtm_error_callback(0);
		}

		/* Status byte - bitfield: Bit 7 = REBURST_REQ, Bits 6:1 = Reserved, Bit 0 = Detect */
		if ((0u != (qtlib_key_set1.qtm_touch_key_group_data->qtm_keys_status & QTM_KEY_REBURST/*0x80u*/))) {
			// Reburst
			/* USE_MPTT_WRAPPER */
			// time_to_measure_touch_flag = 1u;
			qlib_touch_flag = QTLIB_STATE_ACTIVE;
		} else {
			measurement_done_touch = 1u;
#if (DEF_TOUCH_LOWPOWER_ENABLE == 1u)
			if (0u != (qtlib_key_grp_data_set1.qtm_keys_status & QTM_KEY_DETECT)) {
				/* Something in detect, clear */
				time_since_touch = 0u;
			}
#endif
			touch_process_lowpower();
		}

#ifdef DEF_TOUCH_DATA_STREAMER_ENABLE
		datastreamer_output();
#endif
	}
	
#if (DEF_TOUCH_LOWPOWER_ENABLE == 1u)
	// if (time_to_measure_touch_flag != 1u) {
	/* USE_MPTT_WRAPPER */
#endif
		
	return qlib_touch_flag == QTLIB_STATE_ACTIVE;
}

void touch_set_scan_rate(void) 
{
	uint8_t set_rate = 0;
	
	if (qlib_touch_flag == QTLIB_STATE_SLEEP) {
		if (measurement_active_to_idle != 0) {	// External command force exit sleep mode
			qlib_touch_flag = QTLIB_STATE_ACTIVE;
		}
	}
	
	if (qlib_touch_flag != QTLIB_STATE_SLEEP) {
		if (qlib_lowpower_flag == 1) {	// Exit low power mode
			/* Cancel node auto scan */
			qtm_autoscan_node_cancel();

			/* disable event system measurement */
			touch_disable_lowpower_measurement();
				
			qlib_lowpower_flag = 0;
			
			set_rate = 1;
		}
		
		if (measurement_period_store != measurement_period_active_store) {
			if (measurement_period_active_store == 0) {
				// Disable scan only in complete
				if (qlib_touch_flag == QTLIB_STATE_COMPLETE) {
					set_rate = 1;
				}
			}else {
				// change rate at wake up mode
				if (qlib_touch_flag != QTLIB_STATE_SLEEP) {
					set_rate = 1;
				}
			}
		}
		
		if (set_rate) {
			measurement_period_store = measurement_period_active_store;
			Timer_set_period(measurement_period_store, false);
		}
	}
}

#if (DEF_TOUCH_LOWPOWER_ENABLE == 1u)

/*============================================================================
static void touch_disable_lowpower_measurement(void)
------------------------------------------------------------------------------
Purpose:	enter into active mode
Input  : none
Output : none
Notes  :
============================================================================*/
/* USE_MPTT_WRAPPER */
static void touch_disable_lowpower_measurement(void)
{
	/* Disable RTC to PTC Event system */
	EVSYS.ASYNCCH3   = EVSYS_ASYNCCH3_OFF_gc;
	EVSYS.ASYNCUSER1 = EVSYS_ASYNCUSER1_OFF_gc;
}

/*============================================================================
static void touch_enable_lowpower_measurement(void)
------------------------------------------------------------------------------
Purpose:
Input  : none
Output : none
Notes  :
============================================================================*/
/* USE_MPTT_WRAPPER */
static void touch_enable_lowpower_measurement(void)
{
	uint8_t i;
	
	if (measurement_period_idle_store != 0) {
		for (i = 0; i < NODE_SLEEP_SCAN_RATE_LEVELS; i++) {
			if (measurement_period_idle_store <= (2 << i))
				break;
		}
	
		/* Set source of event channel with autoscan Periodic Interval  */
		EVSYS.ASYNCCH3   = (EVSYS_ASYNCCH3_PIT_DIV64_gc - i);
		EVSYS.ASYNCUSER1 = EVSYS_ASYNCUSER1_ASYNCCH3_gc; /* Asynchronous Event Channel 3 */
	}
}

/*============================================================================
static void touch_process_lowpower(void)
------------------------------------------------------------------------------
Purpose: Processing function enter into sleep mode
         Monitors the touch activity and if there is not touch for longer
         duration, low-power autoscan is enabled.
Input  : none
Output : none
Notes  :
============================================================================*/
static void touch_process_lowpower(void)
{
	touch_ret_t touch_ret;
	int16_t wdt_period;
	uint8_t drift_rate;

	if (measurement_active_to_idle &&
		(measurement_active_to_idle * 200) < time_since_touch) {	// Enter into low power mode
		
		qlib_touch_flag = QTLIB_STATE_SLEEP;

		/* Start Autoscan */
		touch_ret = qtm_autoscan_sensor_node(&auto_scan_setup, touch_measure_wcomp_match);
		if (touch_ret == TOUCH_SUCCESS) {
			//qlib_touch_flag = QTLIB_STATE_LOW_POWER_SCANNING;
			qlib_lowpower_flag = 1;	
			/* Enable Event System */
			touch_enable_lowpower_measurement();
			
			// For drift measurement
			drift_rate = qtlib_key_grp_config_set1.sensor_touch_drift_rate;
			if (!drift_rate)
				drift_rate = DEF_TCH_DRIFT_RATE;
			
			measurement_period_store = (uint16_t)qtlib_key_grp_config_set1.sensor_touch_drift_rate * 200;
#ifdef USE_WDT
			wdt_period = (int16_t)WDT_0_get_period_value();
			if (wdt_period) {
				wdt_period -= DEF_WDT_FEEDING_MARGIN;	// Get WDT margin
				if (wdt_period < 0)
					wdt_period = 1;	// Fastest
				if (measurement_period_store > wdt_period)
					measurement_period_store = wdt_period;
				CLR_WDT();
			}
#endif
			Timer_set_period(measurement_period_store, true);
		}
	}
}

/*============================================================================
static void touch_measure_wcomp_match(void)
------------------------------------------------------------------------------
Purpose: callback of autoscan function
Input  : none
Output : none
Notes  :
============================================================================*/
void touch_measure_wcomp_match(void)
{
	if (qlib_touch_flag == QTLIB_STATE_SLEEP) {
		touch_cancel_autoscan();
		/* USE_MPTT_WRAPPER */
		// time_to_measure_touch_flag = 1u;
		qlib_touch_flag = QTLIB_STATE_ACTIVE;
		time_since_touch           = 0u;
	}
}
/*============================================================================
static void touch_cancel_autoscan(void)
------------------------------------------------------------------------------
Purpose: cancelling of autoscan functionality
Input  : none
Output : none
Notes  :
============================================================================*/
static void touch_cancel_autoscan(void)
{
	/* disable event system measurement */
	touch_disable_lowpower_measurement();
}

#endif


#ifdef OBJECT_T18
extern bool object_t18_check_dismntr(void);
#endif

#ifdef MPTT_BUS_MONITOR
extern void mptt_bus_monitor_ticks(uint8_t tick);
#endif

#include "atmel_start_pins.h"

/*============================================================================
void touch_timer_handler(void)
------------------------------------------------------------------------------
Purpose: This function updates the time elapsed to the touch key module to
         synchronize the internal time counts used by the module.
Input  : none
Output : none
Notes  :
============================================================================*/
void touch_timer_handler(void)
{
#ifdef OBJECT_T25
	if (qlib_touch_flag == QTLIB_STATE_SUSPEND)
		return;
#endif

	// Update bit heart to bus monitor
#ifdef MPTT_BUS_MONITOR
#ifdef OBJECT_T18
	if (!object_t18_check_dismntr())
#endif
		mptt_bus_monitor_ticks(measurement_period_store);
#endif
	
	/* Count complete - Measure touch sensors */
	/* USE_MPTT_WRAPPER */
	// time_to_measure_touch_flag = 1u;
	qlib_touch_flag = QTLIB_STATE_ACTIVE;
	
#if (DEF_TOUCH_LOWPOWER_ENABLE == 1u)

	if (time_since_touch < (65535u - measurement_period_store)) {
		time_since_touch += measurement_period_store;
	} else {
		time_since_touch = 65535;
	}
#else
	/* USE_MPTT_WRAPPER */
	// qtm_update_qtlib_timer(DEF_TOUCH_MEASUREMENT_PERIOD_MS);
#endif

	qtm_update_qtlib_timer(measurement_period_store);	
}

uint16_t get_sensor_node_signal(uint16_t sensor_node)
{
	return (ptc_qtlib_node_stat1[sensor_node].node_acq_signals);
}

void update_sensor_node_signal(uint16_t sensor_node, uint16_t new_signal)
{
	ptc_qtlib_node_stat1[sensor_node].node_acq_signals = new_signal;
}

uint16_t get_sensor_node_reference(uint16_t sensor_node)
{
	return (qtlib_key_data_set1[sensor_node].channel_reference);
}

void update_sensor_node_reference(uint16_t sensor_node, uint16_t new_reference)
{
	qtlib_key_data_set1[sensor_node].channel_reference = new_reference;
}

uint16_t get_sensor_cc_val(uint16_t sensor_node)
{
	return (ptc_qtlib_node_stat1[sensor_node].node_comp_caps);
}

void update_sensor_cc_val(uint16_t sensor_node, uint16_t new_cc_value)
{
	ptc_qtlib_node_stat1[sensor_node].node_comp_caps = new_cc_value;
}

uint8_t get_sensor_state(uint16_t sensor_node)
{
	return (qtlib_key_set1.qtm_touch_key_data[sensor_node].sensor_state);
}

void update_sensor_state(uint16_t sensor_node, uint8_t new_state)
{
	qtlib_key_set1.qtm_touch_key_data[sensor_node].sensor_state = new_state;
}

void calibrate_node(uint16_t sensor_node)
{
	/* Calibrate Node */
	qtm_calibrate_sensor_node(&qtlib_acq_set1, sensor_node);
	/* Initialize key */
	qtm_init_sensor_key(&qtlib_key_set1, sensor_node, &ptc_qtlib_node_stat1[sensor_node]);
}

void touch_suspend(uint8_t suspend) 
{
	if (suspend)
		qlib_touch_flag = QTLIB_STATE_SUSPEND;
	else
		qlib_touch_flag = QTLIB_STATE_IDLE;
}

/*============================================================================
ISR(ADC0_RESRDY_vect)
------------------------------------------------------------------------------
Purpose:  Interrupt handler for ADC / PTC EOC Interrupt
Input    :  none
Output  :  none
Notes    :  none
============================================================================*/
ISR(ADC0_RESRDY_vect)
{
#ifdef OBJECT_T25
	if (qlib_touch_flag == QTLIB_STATE_SUSPEND)
		return;
#endif

	qtm_t321x_ptc_handler_eoc();
}

/*============================================================================
ISR(ADC0_WCOMP_vect)
------------------------------------------------------------------------------
Purpose:  Interrupt handler for ADC / PTC WCOMP Interrupt
Input    :  none
Output  :  none
Notes    :  none
============================================================================*/
ISR(ADC0_WCOMP_vect)
{
#ifdef OBJECT_T25
	if (qlib_touch_flag == QTLIB_STATE_SUSPEND)
		return;
#endif

	qtm_t321x_ptc_handler_wcomp();
}

#endif /* TOUCH_C */
