/*
 * tslapi.h
 *
 * Created: 6/15/2019 2:37:52 PM
 *  Author: A41450
 */ 


#ifndef TSLAPI_H_
#define TSLAPI_H_

enum {
	DEF_TOUCH_MEASUREMENT_PERIOD_MS = 0,
	DEF_SENSOR_TYPE,
	DEF_PTC_CAL_OPTION,
	DEF_PTC_INTERRUPT_PRIORITY,
	DEF_PTC_TAU_TARGET,
	DEF_PTC_CAL_AUTO_TUNE,
	DEF_SEL_FREQ_INIT,

	NUM_CHANNELS,
	NUM_SENSORS,
	NODE_PARAMS_CSD,
	NODE_PARAMS_RESISTOR_PRESCALER,
	NODE_PARAMS_GAIN,
	NODE_PARAMS_ADC_OVERSAMPLING,

	KEY_PARAMS_THRESHOLD,
	KEY_PARAMS_HYSTERESIS,
	KEY_PARAMS_AKS_GROUP,

	DEF_TOUCH_DET_INT,
	DEF_ANTI_TCH_DET_INT,
	DEF_ANTI_TCH_RECAL_THRSHLD,
	DEF_TCH_DRIFT_RATE,
	DEF_ANTI_TCH_DRIFT_RATE,
	DEF_DRIFT_HOLD_TIME,
	DEF_REBURST_MODE,
	DEF_MAX_ON_DURATION,
	
	SURFACE_CS_START_KEY_H,
	SURFACE_CS_NUM_KEYS_H,
	SURFACE_CS_START_KEY_V,
	SURFACE_CS_NUM_KEYS_V,
	SURFACE_CS_RESOL_DB,
	SURFACE_CS_FILT_CFG,
	SURFACE_CS_POS_HYST,
	SURFACE_CS_MIN_CONTACT,
	
	TAP_RELEASE_TIMEOUT,
	TAP_HOLD_TIMEOUT,
	SWIPE_TIMEOUT,
	HORIZONTAL_SWIPE_DISTANCE_THRESHOLD,
	VERTICAL_SWIPE_DISTANCE_THRESHOLD,
	TAP_AREA,
	SEQ_TAP_DIST_THRESHOLD,
	EDGE_BOUNDARY,
	WHEEL_POSTSCALER,
	WHEEL_START_QUADRANT_COUNT,
	WHEEL_REVERSE_QUADRANT_COUNT,
	DEF_GESTURE_TIME_BASE_MS,
	
	NUM_FREQ_STEPS,
	DEF_MEDIAN_FILTER_FREQUENCIES,
	DEF_FREQ_AUTOTUNE_ENABLE,
	FREQ_AUTOTUNE_MAX_VARIANCE,
	FREQ_AUTOTUNE_COUNT_IN,
};


typedef ssint (*cb_writeback_t)(u8 type, const void *src, size_t size, u8 index);

#endif /* TSLAPI_H_ */