/*============================================================================
Filename : touch_api_adc.h
Project : Mtouch Modular Library
Purpose : Includes the Module API header files based on the configured modules,
          prototypes for touch.c file and Application helper API functions

This file is part of Mtouch Modular Library Release 1.0 application.

Important Note: Do not edit this file manually.
                Use Mtouch Configurator within Atmel Start to apply any
                modifications to this file.

Usage License: Refer license.h file for license information
Support: Visit http://www.microchip.com/support/hottopics.aspx
               to create MySupport case.

------------------------------------------------------------------------------
Copyright (c) 2021 Microchip. All rights reserved.
------------------------------------------------------------------------------
============================================================================*/

#ifndef TOUCH_API_ADC_H
#define TOUCH_API_ADC_H

#include "qtm_common_components_api.h"
#include "qtm_acq_q10_0x001b_api.h"
#include "qtm_freq_hop_0x0006_api.h"
#include "qtm_touch_key_0x0002_api.h"

/*----------------------------------------------------------------------------
 *   prototypes
 *----------------------------------------------------------------------------*/
/* Application Helper API's */

void  touch_timer_handler(void);
void  touch_init(void);
void  touch_process(void);
uint8_t  touch_sleep(void);
void  touch_suspend(uint8_t suspend);
void  touch_inject_event(void);
int8_t  touch_state_idle(void);
int8_t  touch_state_sleep(void);
void  touch_calibrate(void);
void  touch_init_sensor(void);
#endif