/*============================================================================
Filename : touch.c
Project : Mtouch Modular Library
Purpose : Provides Initialization, Processing and ISR handler of touch library,
          Simple API functions to get/set the key touch parameters from/to the
          touch library data structures

This file is part of Mtouch Modular Library Release 1.0 application.

Important Note: Do not edit this file manually.
                Use Mtouch Configurator within Atmel Start to apply any
                modifications to this file.

Usage License: Refer license.h file for license information
Support: Visit http://www.microchip.com/support/hottopics.aspx
               to create MySupport case.

------------------------------------------------------------------------------
Copyright (c) 2021 Microchip. All rights reserved.
------------------------------------------------------------------------------
============================================================================*/
#ifndef TOUCH_C
#define TOUCH_C

/*----------------------------------------------------------------------------
 *     include files
 *----------------------------------------------------------------------------*/

#include <xc.h>
#include <mcc.h>

#include <common/include/types.h>
#include <utils/compiler_included.h>

#include "arch/cpu.h"
#include "arch/pinconf.h"
#include "arch/timer.h"
#include "arch/sysctrl.h"

#include "arch/tslink.h"
#include "lib/tslib.h"
#include "touch.h"

/*----------------------------------------------------------------------------
 *   prototypes
 *----------------------------------------------------------------------------*/

/*! \brief configure the ptc port pins to Input
 */
/* static */void touch_ptc_pin_config(void);

/*! \brief configure keys, wheels and sliders.
 */
static void touch_sensors_config(void);

/*! \brief Touch measure complete callback function example prototype.
 */
static void touch_measure_complete_callback(void);

/*! \brief Touch Error callback function prototype.
 */
static void touch_error_callback(uint8_t error);

#if (DEF_TOUCH_LOWPOWER_ENABLE == 1u)
/* low power processing function */
static bool touch_process_autoscan(void);

/* low power touch detection callback */
static void touch_measure_wcomp_match(void);

/* Set autoscan measurement */
static touch_ret_t touch_autoscan_sensor_node_soft(void);
static touch_ret_t touch_autoscan_sensor_node_evsys(qtm_auto_scan_config_t* qtm_auto_scan_config_ptr, void (*auto_scan_callback)(void));

/* Cancel autoscan measurement */
static void touch_autoscan_node_cancel(void);

/* measurement evsys enable */
static void touch_evsys_enable(void);

/* measurement evsys cancel */
static void touch_evsys_cancel(void);

/* low power measurement read current lowpower button delta */
static delta_t touch_read_lp_button_delta(void);

/* low power measurement read current lowpower button state */
static int8_t touch_read_lp_button_state(void);
#endif

/* Handle the scanning state of measurement */
static void touch_handle_measurement_state(void);

/* Handle the calibration state of measurement */
static void touch_handle_calibration(void);

/* Handle the scanning measurement */
static void touch_handle_measurement(void);

/* Handle the scanning result of measurement */
static void touch_handle_acquisition_process(void);

/* Handle acqusition timer event */
void touch_timer_handler(void);

/* Handle ADC acqusition isr */
void ISR_ADC0_RESRDY_vect(void);

#ifndef DEF_TOUCH_LOWPOWER_SOFT
/* Handle ADC window comparator isr */
void ISR_ADC0_WCOMP_vect(void);
#endif

/*----------------------------------------------------------------------------
 *     Global Variables
 *----------------------------------------------------------------------------*/
/* USE_MPTT_WRAPPER 
  qlib_touch_state state machine, default zero for all
*/

// lib suspend, not working or in other mode like ADC
DECLARE_STATIC_GLOBAL_FLAG(qlib_touch_state, QTLIB_STATE_SUSPEND);
// lib at sleep mode
DECLARE_STATIC_GLOBAL_FLAG(qlib_touch_state, QTLIB_STATE_SLEEP);
// lib get wakeup instruction but still enter into sleep later
DECLARE_STATIC_GLOBAL_FLAG(qlib_touch_state, QTLIB_STATE_SLEEP_WALK);
// lib get active instruction and prepare to exit sleep mode
DECLARE_STATIC_GLOBAL_FLAG(qlib_touch_state, QTLIB_STATE_SLEEP_PRE_EXIT);
// lib in normal mode, in measurement
DECLARE_STATIC_GLOBAL_FLAG(qlib_touch_state, QTLIB_STATE_ACTIVE);
// lib in normal mode, and start to measure
DECLARE_STATIC_GLOBAL_FLAG(qlib_touch_state, QTLIB_STATE_TIME_TO_MEASURE);
// lib in normal mode, and measurement done
DECLARE_STATIC_GLOBAL_FLAG(qlib_touch_state, QTLIB_STATE_MEASUREMENT_DONE);
// lib interrupted by external event
DECLARE_STATIC_GLOBAL_FLAG(qlib_touch_state, QTLIB_STATE_EXTERNAL_EVENT);

/* Flag to indicate time for touch measurement */
// volatile uint8_t time_to_measure_touch_flag = 0;

/* postporcess request flag */
// volatile uint8_t touch_postprocess_request = 0;

/* Measurement Done Touch Flag  */
volatile uint8_t measurement_done_touch = 0;

/* USE_MPTT_WRAPPER 
  qlib_measurement_state state machine
*/

volatile uint8_t qlib_measurement_state = 0;

// Do calibration for nodes
#define MEASUREMENT_CAL_REQ    0
// Initialize key parameters
#define MEASUREMENT_INIT_SENSOR_REQ    1
// Initialize slider parameters
#define MEASUREMENT_INIT_SLIDER_REQ    2
// Initialize surface parameters
#define MEASUREMENT_INIT_SURFACE_REQ  3

/* Error Handling */
uint8_t module_error_code = 0;

/* Low-power measurement variables, store how long last touch elapsed, unit: ms 
  initialized as 0
*/
uint16_t time_since_touch = 0;
/*  USE_MPTT_WRAPPER:
  set 3 varibles for the measurement period: active and idle by `measurement_period_store`
  `measurement_period_store`: current used measurement period
  `measurement_period_active_store`: active measurement period setting
  `measurement_period_idle_store`: idle measurement period setting(for low power mode)
  */
uint16_t measurement_period_store = DEF_TOUCH_MEASUREMENT_PERIOD_MS;
/*
  USE_MPTT_WRAPPER:
  Active Acquisition Interval
  Range: [0~255], unit 1ms
  0: suspend
  1 ~ 255: actual value with 1ms unit
  */
uint8_t measurement_period_active_store = DEF_TOUCH_MEASUREMENT_PERIOD_MS;

/*  
  USE_MPTT_WRAPPER:
  Idle Acquisition Interval
  0: disable sleep mode  
  1 ~ 255: actual value with 1ms unit
*/
uint8_t measurement_period_idle_store = DEF_TOUCH_MEASUREMENT_IDLE_PERIOD_MS;

/*
  USE_MPTT_WRAPPER:
  The Active to Idle Timeout from last touch.
  Range: [0~255], unit 200ms
  0: means never enter into idle automatically
  1 ~ 255: actual value with 200ms unit
*/
uint8_t measurement_active_to_idle = DEF_TOUCH_ACTIVE_IDLE_TIMEOUT;

/*
  USE_MPTT_WRAPPER:
  Idle Drift Interval
  0: disabled in sleep mode  
  1 ~ 255: actual value with 200ms unit. 
  Note: maximum value limited by watchdog window period
*/
uint8_t measurement_period_idle_drift = DEF_TOUCH_DRIFT_PERIOD_MS;

#if (DEF_TOUCH_LOWPOWER_ENABLE == 1u)
#ifdef DEF_TOUCH_LOWPOWER_SOFT
/* Low-power measurement sensor(key) node currently, it will change for next scanning channel if multi channel enabled in low power mode
  initialized as -1 (thenm next check will be channel 0)
*/
uint8_t current_autoscan_sensor_soft = (uint8_t)-1;

/* Low-power measurement variables, store how long last drift elapsed, unit: ms 
  initialized as 0
*/
uint16_t time_since_last_drift = 0;
#endif
#endif

/*
  Touch measurement overflow counter, to record how many times of the acquisition overflows
*/
#ifdef DEF_TOUCH_MEASUREMENT_OVERFLOW
static uint8_t touch_measurement_overflow;
#endif

/* Acquisition module internal data - Size to largest acquisition set */
signal_t qtm_acq_signals_raw1[DEF_NUM_CHANNEL_NODES];

/* Acquisition set 1 - General settings */
qtm_acq_node_group_config_t qtm_acq_gen1
    = {DEF_NUM_CHANNEL_NODES, DEF_SENSOR_TYPE, DEF_PTC_CAL_AUTO_TUNE, DEF_SEL_FREQ_INIT};

/* Node configurations */
qtm_acq_node_config_t qtm_seq_node_cfg1[DEF_NUM_CHANNEL_NODES] = PTC_SEQ_NODE_CFG1;

/* Node status, signal, calibration values */
qtm_acq_node_data_t qtm_node_stat1[DEF_NUM_CHANNEL_NODES];

/* Node Container */
qtm_acquisition_control_t qtlib_acq_set1 = {&qtm_acq_gen1, &qtm_seq_node_cfg1[0], &qtm_node_stat1[0], &qtm_acq_signals_raw1[0]};

#if (DEF_TOUCH_LOWPOWER_ENABLE == 1u)
/* Low-power autoscan related parameters */
qtm_auto_scan_config_t auto_scan_setup
    = {&qtlib_acq_set1, QTM_AUTOSCAN_NODE, QTM_AUTOSCAN_THRESHOLD, /*QTM_AUTOSCAN_TRIGGER_PERIOD*/0};
#endif

/**********************************************************/
/*********** Frequency Hop Module **********************/
/**********************************************************/

/* Buffer used with various noise filtering functions */
signal_t qtm_noise_filter_buffer[DEF_NUM_CHANNEL_NODES * NUM_FREQ_STEPS];
uint8_t  qtm_freq_hop_delay_selection[NUM_FREQ_STEPS] = {DEF_MEDIAN_FILTER_FREQUENCIES};

/* Configuration */
qtm_freq_hop_config_t qtm_freq_hop_config1 = {
    DEF_NUM_CHANNEL_NODES,
    NUM_FREQ_STEPS,
    &qtm_acq_gen1.freq_option_select,
    &qtm_freq_hop_delay_selection[0],
};

/* Data */
qtm_freq_hop_data_t qtm_freq_hop_data1 = {0, 0, &qtm_noise_filter_buffer[0], &qtm_node_stat1[0]};

/* Freq Hop Container */
qtm_freq_hop_control_t qtlib_freq_hop_set1 = {&qtm_freq_hop_data1, &qtm_freq_hop_config1};

/**********************************************************/
/*********************** Keys Module **********************/
/**********************************************************/

/* Keys set 1 - General settings */
qtm_touch_key_group_config_t qtm_key_grp_config_set1 = {DEF_NUM_SENSORS,
                                                          DEF_TOUCH_DET_INT,
                                                          DEF_MAX_ON_DURATION,
                                                          DEF_ANTI_TCH_DET_INT,
                                                          DEF_ANTI_TCH_RECAL_THRSHLD,
                                                          DEF_TCH_DRIFT_RATE,
                                                          DEF_ANTI_TCH_DRIFT_RATE,
                                                          DEF_DRIFT_HOLD_TIME,
                                                          DEF_REBURST_MODE};

qtm_touch_key_group_data_t qtm_key_grp_data_set1;

/* Key data */
qtm_touch_key_data_t qtm_key_data_set1[DEF_NUM_SENSORS];

/* Key Configurations */
qtm_touch_key_config_t qtm_key_configs_set1[DEF_NUM_SENSORS] = QTLIB_KEY_CONFIGS_SET;

/* Key Container */
qtm_touch_key_control_t qtlib_key_set1
    = {&qtm_key_grp_data_set1, &qtm_key_grp_config_set1, &qtm_key_data_set1[0], &qtm_key_configs_set1[0]};


/*============================================================================
void touch_non_sensor_pin_config(void)
------------------------------------------------------------------------------
Purpose: Initialization of non sensor pins
Input  : none
Output : none
Notes  :
============================================================================*/
static void touch_non_sensor_pin_config(void)
{
  // Some None sensor pins config here
}

/*============================================================================
void touch_sensor_pin_config(void)
------------------------------------------------------------------------------
Purpose: Initialization of touch sensor pins
Input  : none
Output : none
Notes  :
============================================================================*/
#ifndef MPTT_AUTO_PINMUX
void touch_sensor_pin_config(void)
{
  // Some sensor pins config here
  // Noted, if using auto pinmux feature, this function is achieved in `pinconf.c`
}
#endif

/*============================================================================
static void touch_module_config(void)
------------------------------------------------------------------------------
Purpose: Initialization of touch module
Input  : none
Output : none
Notes  :
============================================================================*/
/* Touch sensors config - initialize the touch sensors */
static void touch_module_config(void)
{
  // initialize tslib
  tslib_init();

  // register adc interrupt handler
  tslib_set_adc_isr_handler(ISR_ADC0_RESRDY_vect);
  //tslib_set_wcomp_isr_handler(ISR_ADC0_WCOMP_vect);

#if (DEF_TOUCH_LOWPOWER_ENABLE == 1u)
#ifndef DEF_TOUCH_LOWPOWER_SOFT
  // register wcomp interrupt handler
  //tslib_set_wcomp_isr_handler(ISR_ADC0_WCOMP_vect);
#endif
#endif
}

/*============================================================================
static void touch_measure_complete_callback( void )
------------------------------------------------------------------------------
Purpose: this function is called after the completion of
         measurement cycle. This function sets the post processing request
         flag to trigger the post processing.
Input  : none
Output : none
Notes  :
============================================================================*/
static void touch_measure_complete_callback(void)
{
  // touch_postprocess_request = 1u;

  /* USE_MPTT_WRAPPER */
  SET(qlib_touch_state, QTLIB_STATE_MEASUREMENT_DONE);
}

/*============================================================================
static void touch_error_callback(uint8_t error)
------------------------------------------------------------------------------
Purpose: this function is used to report error in the modules.
Input  : error code
Output : decoded module error code
Notes  :
Derived Module_error_codes:
    Acquisition module error =1
    post processing module1 error = 2
    post processing module2 error = 3
    ... and so on
============================================================================*/
static void touch_error_callback(uint8_t error)
{
  module_error_code = error + 1u;

  // return done error that make the state machine continue running
  measurement_done_touch = 2;

#ifdef DEF_TOUCH_DATA_STREAMER_ENABLE
  datastreamer_output();
#endif
}

/*============================================================================
void touch_init(void)
------------------------------------------------------------------------------
Purpose: Initialization of touch library. PTC, timer, and
         datastreamer modules are initialized in this function.
Input  : none
Output : none
Notes  :
============================================================================*/
void touch_init(void)
{
  /* set the timer interrupt handler */
  Timer_set_callback(touch_timer_handler);

  /* configure the non-Sensor pins */
  touch_non_sensor_pin_config();
  
  /* configure the Sensor pins for Input*/
  touch_sensor_pin_config();

  /* Configure touch module with Application specific settings */
  touch_module_config();
  
#ifdef DEF_TOUCH_DATA_STREAMER_ENABLE
  tslib_datastreamer_init();
#endif
}

/*============================================================================
void touch_start(void)
------------------------------------------------------------------------------
Purpose: Start touch process. sampling timer are started in this function.
Input  : none
Output : none
Notes  :
============================================================================*/
void touch_start(void)
{
  SET(qlib_touch_state, QTLIB_STATE_TIME_TO_MEASURE);
  
  Timer_set_period(measurement_period_store, true);
}

/*============================================================================
uint8_t touch_process(void)
------------------------------------------------------------------------------
Purpose: Main processing function of touch library. This function initiates the
         acquisition, calls post processing after the acquisition complete and
         sets the flag for next measurement based on the sensor status.
Input  : none
Output : None Zero touch is busy, Zero means idle
Notes  :
============================================================================*/
extern int8_t tslink_read_button_state(uint8_t index);
void touch_process(void)
{  
  if (TEST(qlib_touch_state, QTLIB_STATE_SUSPEND))
    return;
  
  /* USE_MPTT_WRAPPER 
    set the scanning rate before touch scanning */  
  touch_handle_measurement_state();
  
  /* USE_MPTT_WRAPPER 
    process calibration */  
  touch_handle_calibration();
  
  /* check the flag for node level post processing */
  touch_handle_acquisition_process();
  
  /* check the flag for measurement */
  touch_handle_measurement();
}

/*============================================================================
uint8_t touch_post_process(void)
------------------------------------------------------------------------------
Purpose: Post processing function of touch library. This function calls post processing after the touch process complete 
Input  : none
Output : None Zero touch is busy, Zero means idle
Notes  :
============================================================================*/
void touch_done(void)
{

#ifdef DEF_TOUCH_DATA_STREAMER_ENABLE
  datastreamer_output();
#endif

  tslib_done();
}

/*============================================================================
USE_MPTT_WRAPPER
u8 touch_sleep(void)
------------------------------------------------------------------------------
Purpose: Indicate whether the touch is busy now, outside could decide whether enter into sleep mode
Input  : none
Output : sleep_mode_t type
Notes  :
============================================================================*/

u8 touch_sleep(void)
{
  sleep_mode_t mode = SLEEP_NONE;

  if (TEST(qlib_touch_state, QTLIB_STATE_SUSPEND))
    return mode;

  // Check deep sleep condition
#if (DEF_TOUCH_LOWPOWER_ENABLE == 1u)
  if (!TEST(qlib_touch_state, QTLIB_STATE_ACTIVE) && 
    !TEST(qlib_touch_state, QTLIB_STATE_TIME_TO_MEASURE)) {
    if (TEST(qlib_touch_state, QTLIB_STATE_SLEEP)) {
      // Last state in sleep already
      mode = SLEEP_DEEP;
    } else {  
      if (touch_process_autoscan()) {
        mode = SLEEP_DEEP;
      }
    }
  }
#endif

  // Check doze sleep condition
  if (mode == SLEEP_NONE) {
    if (TEST(qlib_touch_state, QTLIB_STATE_SLEEP_WALK) ||
      TEST(qlib_touch_state, QTLIB_STATE_TIME_TO_MEASURE) ||
      /* TEST(qlib_touch_state, QTLIB_STATE_ACTIVE) || */
      TEST(qlib_touch_state, QTLIB_STATE_MEASUREMENT_DONE)) {
        // Active
    } else {
      mode = SLEEP_DOZE;
    }
  }

  return mode;
}

/*============================================================================
USE_MPTT_WRAPPER
void get_next_measurement_period(void)
------------------------------------------------------------------------------
Purpose: Get next measurement compared to wdt period
Input  : current period
Output : next measurement
Notes  :
============================================================================*/

uint16_t get_next_measurement_period(uint16_t current)
{
#if USE_WDT
  uint16_t wdt_period;
  
  wdt_period = sys_get_wdt_period();
  if (wdt_period) {
#define DEF_WDT_FEEDING_MARGIN 40	//ms
    if (wdt_period <= DEF_WDT_FEEDING_MARGIN) {
      wdt_period = 1; // Fastest
    } else {
      wdt_period -= DEF_WDT_FEEDING_MARGIN;
    }

    /* if drift disabled(0), or drift interval slow than wdt, set to wdt period with margin*/
    if (!current || current > wdt_period) {
      current = wdt_period;
    }
  }
#endif

  return current;
}

/*============================================================================
static void touch_handle_measurement_state(void)
------------------------------------------------------------------------------
Purpose: Handle the scanning state of measurement
Input  : none
Output : none
Notes  :
============================================================================*/
extern bool object_api_t126_lowpower_mode_enabled(void);
extern uint8_t object_api_t25_test_inprogress(void);
extern void object_api_t126_force_waked(int16_t val);
extern void object_api_t126_breach_waked(int16_t val);
static void touch_handle_measurement_state(void)
{  
  uint16_t period;
  
  /* Here we test whether current state in sleep mode, if it is:
    <1> it's drift cycle, (both QTLIB_STATE_SLEEP and QTLIB_STATE_TIME_TO_MEASURE is set), we just do lowpower config switched to normal config, but keep flags
    <2> it's pre-exit status or external command forced exit, we will clear all other flag and set to active
   */
#if (DEF_TOUCH_LOWPOWER_ENABLE == 1u)
  // In sleep
  if (TEST(qlib_touch_state, QTLIB_STATE_SLEEP)) {  
    /* check whether exit autoscan mode */
    
    /* touch detection exit */
    if (TEST(qlib_touch_state, QTLIB_STATE_SLEEP_PRE_EXIT)) {
	  /* could do something for pre-exit */
      /* notice t126 register the status changed */
      // object_api_t126_breach_waked(touch_read_lp_button_delta());
    } else {
      /* `QTLIB_STATE_EXTERNAL_EVENT`
          external T7 command forced exit or
          external T126 disable force exit
      */
      if (qlib_measurement_state 
        || !measurement_active_to_idle 
        || !object_api_t126_lowpower_mode_enabled() 
#ifdef OBJECT_T25
        || object_api_t25_test_inprogress()
#endif
      ) {
        /* notice t126 register the status changed */
        object_api_t126_force_waked(0);      
      } else {
        /* invalid external event */
        CLR(qlib_touch_state, QTLIB_STATE_EXTERNAL_EVENT);
      }
    }
    
    if (TEST(qlib_touch_state, QTLIB_STATE_SLEEP_PRE_EXIT) || TEST(qlib_touch_state, QTLIB_STATE_EXTERNAL_EVENT)) {
      /* Clear all flag and start to measure */
      SET(qlib_touch_state, QTLIB_STATE_TIME_TO_MEASURE);
      CLR(qlib_touch_state, QTLIB_STATE_SLEEP_WALK);
      CLR(qlib_touch_state, QTLIB_STATE_SLEEP);
    } else if (TEST(qlib_touch_state, QTLIB_STATE_SLEEP_WALK)) {
      /* In sleep walk, wake up */
      CLR(qlib_touch_state, QTLIB_STATE_SLEEP);
    }
          
    if (!TEST(qlib_touch_state, QTLIB_STATE_SLEEP)) {
      /* Cancel node auto scan */
      touch_autoscan_node_cancel();
    }
  }
#endif

#if (DEF_TOUCH_LOWPOWER_ENABLE == 1u)
  /* if it's in sleep mode, we set to drift period */
  if (TEST(qlib_touch_state, QTLIB_STATE_SLEEP) || TEST(qlib_touch_state, QTLIB_STATE_SLEEP_WALK)) {
#ifdef DEF_TOUCH_LOWPOWER_SOFT
    // For soft sleep, we measured at each idle cycle
    period = measurement_period_idle_store;
#else
    // For event sleep, we measured at each drift cycle
    period = (uint16_t)measurement_period_idle_drift * 200;
#endif
  } else 
#endif  
  {
  /* if it's not in sleep mode, we will check and set the active measurement period */
    period = measurement_period_active_store;
  }
  
  /* if it's in sleep mode, we will check whether do scanning */
  if (measurement_period_store != period) {  // FIXME: if the idle period is equal active period, we will skip here?
    period = get_next_measurement_period(period);
    if (measurement_period_store  != period) {
      measurement_period_store  = period;
      Timer_set_period(measurement_period_store, true);
    }
    
    if (!period) {
      CLR(qlib_touch_state, QTLIB_STATE_TIME_TO_MEASURE);
    }
  }
  
  CLR(qlib_touch_state, QTLIB_STATE_EXTERNAL_EVENT);
  CLR(qlib_touch_state, QTLIB_STATE_SLEEP_PRE_EXIT);
}

/*============================================================================
static void touch_handle_calibration(void)
------------------------------------------------------------------------------
Purpose: Processing function of the post calibration and channel node initialization
         calibration by sleep mode will be post processed here
Input  : none
Output : none
Notes  :
============================================================================*/
/* USE_MPTT_WRAPPER, 
  We should consider low power mode wakeup time(for drift) and watchdog feeding
 */
static void touch_handle_calibration(void)
{    
  if (!qlib_measurement_state)
    return;
  
  if (TEST(qlib_touch_state, QTLIB_STATE_SLEEP))
    return;
  
  /* process calibration and initialized sensor request */
  
  if (TEST_BIT(qlib_measurement_state, MEASUREMENT_INIT_SENSOR_REQ)) {
    tslib_init_all_sensors();
  }
  
  #ifdef TOUCH_API_SCROLLER_H
  if (TEST_BIT(qlib_measurement_state, MEASUREMENT_INIT_SLIDER_REQ)) {
    tslib_init_all_scroller_module();
  }
  #endif
  
  if (TEST_BIT(qlib_measurement_state, MEASUREMENT_CAL_REQ)) {
    tslib_calibrate_all_sensors();
  }
  
  qlib_measurement_state = 0;
}

/*============================================================================
static void touch_handle_measurement(void)
------------------------------------------------------------------------------
Purpose: Processing function of the measurement
Input  : none
Output : none
Notes  :
============================================================================*/
/* USE_MPTT_WRAPPER, 
  We should consider low power mode wakeup time(for drift) and watchdog feeding
 */
extern void object_api_t6_set_overflow(uint8_t set);
static void touch_handle_measurement(void)
{
  touch_ret_t touch_ret;
  
  /* check the qlib_touch_state flag for Touch Acquisition */
  /* USE_MPTT_WRAPPER,
    Note active flag is one shot after executed
   */
        
  // if (time_to_measure_touch_flag == 1u) {
  if (TEST(qlib_touch_state, QTLIB_STATE_TIME_TO_MEASURE)) {
    /* Clear the Measure request flag */
    CLR(qlib_touch_state, QTLIB_STATE_TIME_TO_MEASURE);  
    /* Do the acquisition */
    touch_ret = tslib_touch_start_measurement_seq(touch_measure_complete_callback);
    /* if the Acquisition request was successful then clear the request flag */
    if (TOUCH_SUCCESS == touch_ret) {
      /* USE_MPTT_WRAPPER */
      // time_to_measure_touch_flag = 0u;
      SET(qlib_touch_state, QTLIB_STATE_ACTIVE);
#ifdef DEF_TOUCH_MEASUREMENT_OVERFLOW
      if (touch_measurement_overflow) {
        touch_measurement_overflow = 0;
      #ifdef OBJECT_T6
        object_api_t6_set_overflow(0);
      #endif
      }
#endif
    } else if (TOUCH_ACQ_INCOMPLETE == touch_ret) {
#ifdef DEF_TOUCH_MEASUREMENT_OVERFLOW
      if (touch_measurement_overflow >= DEF_TOUCH_MEASUREMENT_OVERFLOW_FORCE_DONE) {
        SET(qlib_touch_state, QTLIB_STATE_MEASUREMENT_DONE);
      } else {
        touch_measurement_overflow++;
        if (touch_measurement_overflow >= DEF_TOUCH_MEASUREMENT_OVERFLOW_THRESHOLD) {
      #ifdef OBJECT_T6
          object_api_t6_set_overflow(1);
      #endif
        }
      }
#endif
    } else {
      touch_error_callback(0);
    }
  }
}

/*============================================================================
static void touch_handle_acquisition_process(void)
------------------------------------------------------------------------------
Purpose: Processing function of the measurement
Input  : none
Output : none
Notes  :
============================================================================*/
/* USE_MPTT_WRAPPER, 
  We should consider low power mode wakeup time(for drift) and watchdog feeding
 */
static void touch_handle_acquisition_process(void)
{
  touch_ret_t touch_ret;
  
/* USE_MPTT_WRAPPER  */
  // if (touch_postprocess_request == 1u) {
  if (TEST(qlib_touch_state, QTLIB_STATE_MEASUREMENT_DONE)) {
    /* Reset the flags for node_level_post_processing */
    // touch_postprocess_request = 0u;
    CLR(qlib_touch_state, QTLIB_STATE_MEASUREMENT_DONE);
    CLR(qlib_touch_state, QTLIB_STATE_ACTIVE);

    /* Run Acquisition module level post processing*/
    touch_ret = tslib_acquisition_process();

    /* Check the return value */
    if (TOUCH_SUCCESS == touch_ret) {
      /* Returned with success: Start module level post processing */
      touch_ret = tslib_freq_hop();
      if (TOUCH_SUCCESS != touch_ret) {
        touch_error_callback(touch_ret);
      }

      touch_ret = tslib_key_sensors_process();
      if (TOUCH_SUCCESS != touch_ret) {
        touch_error_callback(touch_ret);
      }
			touch_ret = qtm_surface_cs2t_process(&qtm_surface_cs_control1);
			if (TOUCH_SUCCESS != touch_ret) {
				qtm_error_callback(touch_ret);
			}
			touch_ret = qtm_gestures_2d_process(&qtm_gestures_2d_control1);
			if (TOUCH_SUCCESS != touch_ret) {
				qtm_error_callback(touch_ret);
			}
    } else {
      if (touch_ret == TOUCH_LIB_NODE_CAL_IN_PROCESS) {
        // In calibration, speed it up
        SET(qlib_touch_state, QTLIB_STATE_TIME_TO_MEASURE);
      } else {
        /* Acq module Eror Detected: Issue an Acq module common error code 0x80 */
        touch_error_callback(touch_ret);
      }
    }

    /* Check Reburst */
    if (TOUCH_KEY_REBURST == tslib_key_sensors_reburst()) {
      // Reburst
      /* USE_MPTT_WRAPPER */
      // time_to_measure_touch_flag = 1u;
      SET(qlib_touch_state, QTLIB_STATE_TIME_TO_MEASURE);
    } else {
      measurement_done_touch = 1u;
#if (DEF_TOUCH_LOWPOWER_ENABLE == 1u)
      if (TOUCH_KEY_ACTIVE == tslib_key_sensors_active()) {
        /* Touch in detect, update `time_since_touch` varible
          If in sleep mode, we also should check whether it's the wakeup key pressed(this avoid all keys' drift scanning wakeup) */
        if (TEST(qlib_touch_state, QTLIB_STATE_SLEEP) || TEST(qlib_touch_state, QTLIB_STATE_SLEEP_WALK)) {
          if (touch_read_lp_button_state() > 0) {
#ifdef DEF_TOUCH_LOWPOWER_SOFT
            // Exit autoscan mode if button pressed
            touch_measure_wcomp_match();
#else
            time_since_touch = 0u;
#endif
          }
        } else {
          time_since_touch = 0;
        }
      } else {
        // Touch not detected
      #ifdef DEF_TOUCH_LOWPOWER_SOFT
        // For soft sleep, we switch sensor node before scanning
        if (TEST(qlib_touch_state, QTLIB_STATE_SLEEP)) {
		    	touch_autoscan_sensor_node_soft();
        }
      #endif
      }
#endif
    }
#ifdef DEF_TOUCH_DATA_STREAMER_ENABLE
    datastreamer_output();
#endif
  }
}

#if (DEF_TOUCH_LOWPOWER_ENABLE == 1u)
/*============================================================================
uint8_t get_autoscan_sensor_node(void)
------------------------------------------------------------------------------
Purpose: Get the autoscan sensor node
Input  : none
Output : touch_ret_t
Notes  : none
============================================================================*/
uint8_t get_autoscan_sensor_node(void) 
{
#ifdef DEF_TOUCH_LOWPOWER_SOFT
  return current_autoscan_sensor_soft;
#else
  return (uint8_t)auto_scan_setup.auto_scan_node_number;
#endif
}

#ifdef DEF_TOUCH_LOWPOWER_SOFT
/*============================================================================
uint8_t get_autoscan_sensor_node_mask(void)
------------------------------------------------------------------------------
Purpose: Get the autoscan sensor mask
Input  : none
Output : the node mask (maximum 8 nodes)
Notes  : none
============================================================================*/
uint8_t get_autoscan_sensor_node_mask(void) 
{
  // For soft sleep only
  const uint8_t mask = auto_scan_setup.auto_scan_node_mask;

  return mask;
}

/*============================================================================
static bool sensor_node_is_busy(void)
------------------------------------------------------------------------------
Purpose: check whether key node is busy
Input  : key id
Output : True, busy; false, not idle
Notes  : none
============================================================================*/
static bool sensor_node_is_busy(uint8_t k)
{
  const uint8_t num_key_sensors = tslib_num_key_sensors();
  uint8_t state;

  if (k < num_key_sensors) {
    state = tslib_get_sensor_state(k);
    return (state == QTM_KEY_STATE_CAL) || (state == QTM_KEY_STATE_FILT_IN) || (state == QTM_KEY_STATE_FILT_OUT) ;
  }

  return 0;
}
/*============================================================================
touch_ret_t touch_disable_nonlp_sensors(void)
------------------------------------------------------------------------------
Purpose: Disable
Input  : None
Output : touch_ret_t
Notes  : none
============================================================================*/
static void soft_enable_nonlp_sensors(uint8_t key_mask, bool en)
{
  const uint8_t num_key_sensors = tslib_num_key_sensors();
  uint8_t state;


  for (uint8_t k = 0; k < num_key_sensors; k++) {
    state = tslib_get_sensor_state(k);
    
    if (TEST_BIT(key_mask, k)) {
      if (state == QTM_KEY_STATE_SUSPEND) {
        tslib_key_resume(k);
      }
    } else {
      if (en) {
        if (state == QTM_KEY_STATE_SUSPEND) {
          tslib_key_resume(k);
        }
      } else {
        if (state != QTM_KEY_STATE_SUSPEND) {
          tslib_key_suspend(k);
        }
      }
    }
  }
}

/*============================================================================
static touch_ret_t touch_autoscan_sensor_node_soft(void)
------------------------------------------------------------------------------
Purpose: Configures the PTC for sleep mode measurement of a current sleep node
Input  : none
Output : touch_ret_t
Notes  : none
============================================================================*/
static touch_ret_t touch_autoscan_sensor_node_soft(void) 
{
  const uint8_t num_sensors = tslib_num_key_sensors();
  const uint8_t mask = get_autoscan_sensor_node_mask();
  uint8_t next, key = current_autoscan_sensor_soft;
  
  // Check current key whether busy
  if (key < num_sensors) {
    if (sensor_node_is_busy(key)) {
      return TOUCH_ACQ_INCOMPLETE;
    }
  }

  // Select next low power sensor
  for (uint8_t cnt = key + 1; cnt <= key + num_sensors; cnt++) {
    next = cnt;
    if (next >= num_sensors) {
      next -= num_sensors;
    }
    
    if (TEST_BIT(mask, next)) {
      key = next;
      break;
    }
  }
  
  if (key >= num_sensors) {
    return TOUCH_INVALID_INPUT_PARAM;
  }

  // Disable non-autoscan sensor
  soft_enable_nonlp_sensors(BIT8(key), false);
  
  // Update the autoscan sensor
  current_autoscan_sensor_soft = key;

  return TOUCH_SUCCESS;
}

/*============================================================================
void touch_autoscan_node_cancel_soft(void)
------------------------------------------------------------------------------
Purpose: Cancel auto-scan soft sleep config
Input  : None
Output : None
Notes  : none
============================================================================*/
static void touch_autoscan_node_cancel_soft(void)
{
  const uint8_t num_sensors = tslib_num_key_sensors();
  const uint8_t mask = get_autoscan_sensor_node_mask();
  
  // enable all non-autoscan sensor
  soft_enable_nonlp_sensors(mask, true);
  
  // mask autoscan sensor invalid
  current_autoscan_sensor_soft = num_sensors;
}

#else /* DEF_TOUCH_LOWPOWER_SOFT */
/*============================================================================
static void touch_evsys_cancel(void)
------------------------------------------------------------------------------
Purpose:  enter into active mode
Input  : none
Output : none
Notes  :
============================================================================*/
/* USE_MPTT_WRAPPER, we simplily set EVSYS here */
static void touch_evsys_cancel(void)
{

}

/*============================================================================
static void touch_evsys_enable(void)
------------------------------------------------------------------------------
Purpose:
Input  : none
Output : none
Notes  :
============================================================================*/
/* USE_MPTT_WRAPPER, we simplify set ev-sys here */
static void touch_evsys_enable(void)
{

}

/*============================================================================
static touch_ret_t touch_autoscan_sensor_node_evsys(qtm_auto_scan_config_t* qtm_auto_scan_config_ptr, void (*auto_scan_callback)(void))
------------------------------------------------------------------------------
Purpose: cancelling of autoscan functionality(event system)
Input  : none
Output : none
Notes  :
============================================================================*/
static touch_ret_t touch_autoscan_sensor_node_evsys(qtm_auto_scan_config_t* qtm_auto_scan_config_ptr, void (*auto_scan_callback)(void))
{    
  touch_ret_t touch_ret;
  /* Enable node auto scan */
	touch_ret = tslib_autoscan_sensor_node(qtm_auto_scan_config_ptr, auto_scan_callback);
  if (touch_ret == TOUCH_SUCCESS) {
    /* Enable Event System */
    touch_evsys_enable();  
  }

  return touch_ret;
}

/*============================================================================
static void touch_autoscan_node_cancel_evsys(void)
------------------------------------------------------------------------------
Purpose: cancelling of autoscan functionality
Input  : none
Output : none
Notes  :
============================================================================*/
static void touch_autoscan_node_cancel_evsys(void)
{
  /* Disable event system */
  touch_evsys_cancel();
  
  /* Cancel node auto scan */
  tslib_autoscan_node_cancel();
}

#endif /* DEF_TOUCH_LOWPOWER_SOFT */

/*============================================================================
static void touch_autoscan_node_cancel(void)
------------------------------------------------------------------------------
Purpose: cancelling of autoscan functionality
Input  : none
Output : none
Notes  :
============================================================================*/
static void touch_autoscan_node_cancel(void)
{
#ifdef DEF_TOUCH_LOWPOWER_SOFT
      touch_autoscan_node_cancel_soft();
#else
      touch_autoscan_node_cancel_evsys();
#endif
}


/*============================================================================
int8_t touch_read_lp_button_state(void)
------------------------------------------------------------------------------
Purpose: get lowpower key status
Input  : None
Output : Zero, Not pressed; Large than Zero, pressed, Negative error
Notes  : none
============================================================================*/
static int8_t touch_read_lp_button_state(void)
{
  const uint8_t num_sensors = tslib_num_key_sensors();
  uint8_t sensor;
  int8_t state = 0;
  
#ifdef DEF_TOUCH_LOWPOWER_SOFT
  sensor = current_autoscan_sensor_soft;
#else
  sensor = tslib_get_channel_node_mapping(get_autoscan_sensor_node());
#endif
  
  if (sensor < num_sensors) {
    state = tslink_read_button_state(sensor);
  }
  
  return state;
}

/*============================================================================
delta_t touch_read_lp_button_delta(void)
------------------------------------------------------------------------------
Purpose: get lowpower key delta
Input  : None
Output : current low power button delta
Notes  : none
============================================================================*/
static delta_t touch_read_lp_button_delta(void)
{
  const uint8_t num_sensors = tslib_num_key_sensors();
  uint8_t sensor;
  delta_t val = 0;
  
#ifdef DEF_TOUCH_LOWPOWER_SOFT
  sensor = current_autoscan_sensor_soft;
#else
  sensor = tslib_get_channel_node_mapping(get_autoscan_sensor_node());
#endif

  if (sensor < num_sensors) {
    val = tslib_get_sensor_key_delta(sensor);
  }
  
  return val;
}

/*============================================================================
static void touch_process_autoscan(void)
------------------------------------------------------------------------------
Purpose: Processing function enter into sleep mode
         Monitors the touch activity and if there is not touch for longer
         duration, low-power autoscan is enabled.
Input  : none
Output : bool indicates whether in sleep mode
Notes  :
============================================================================*/
/* USE_MPTT_WRAPPER, 
  We should consider low power mode wakeup time(for drift) and watchdog feeding
 */
extern void object_api_t126_breach_sleep(void);
static bool touch_process_autoscan(void)
{
  touch_ret_t touch_ret;
  uint16_t period;
  bool sleep = false;

  /* T126 object must be enabled */
  if (!object_api_t126_lowpower_mode_enabled())
    return false;

  if (TEST(qlib_touch_state, QTLIB_STATE_SLEEP_WALK)) {
    CLR(qlib_touch_state, QTLIB_STATE_SLEEP_WALK);
    sleep = true;
  } else {
    if (measurement_active_to_idle &&
      (measurement_active_to_idle * 200) < time_since_touch)
    sleep = true;
  }

  /* active to idle timeout none Zero */
  if (sleep) {  // Enter into low power mode
    /* Start Autoscan */
    touch_ret = touch_autoscan_sensor_node_evsys(&auto_scan_setup, touch_measure_wcomp_match);
    if (touch_ret == TOUCH_SUCCESS) {
      /* Ready for Sleep */
      SET(qlib_touch_state, QTLIB_STATE_SLEEP);
      /* notice t126 register the status changed */
      object_api_t126_breach_sleep();
            
      // For drift measurement
#ifdef DEF_TOUCH_LOWPOWER_SOFT
      period = measurement_period_idle_store;
#else
      period = (uint16_t)measurement_period_idle_drift * 200;
#endif

      if (measurement_period_store != period) {  // FIXME: if the idle period is equal active period, we will skip here?
        period = get_next_measurement_period(period);
        if (measurement_period_store  != period) {
          measurement_period_store  = period;
          Timer_set_period(measurement_period_store, true);
        }
      }
    } else {
      sleep = false;
    }
  }

  return sleep;
}

/*============================================================================
static void touch_measure_wcomp_match(void)
------------------------------------------------------------------------------
Purpose: callback of autoscan function
Input  : none
Output : none
Notes  :
============================================================================*/
static void touch_measure_wcomp_match(void)
{
  /* USE_MPTT_WRAPPER
    the Compare mode only used in sleep mode
   */
  if (TEST(qlib_touch_state, QTLIB_STATE_SLEEP)) {
    /* Prepare to exit sleep if the compare interrupt occured */

    /* notice t126 register the status changed */
    object_api_t126_breach_waked((int16_t)touch_read_lp_button_delta());

    // time_to_measure_touch_flag = 1u;
    SET(qlib_touch_state, QTLIB_STATE_SLEEP_PRE_EXIT);
    time_since_touch           = 0u;
  }
}
#endif  /* DEF_TOUCH_LOWPOWER_ENABLE */

/* USE_MPTT_WRAPPER */
#ifdef OBJECT_T25
extern void object_t25_cycling_ticks(uint8_t ticks);
#endif
#ifdef OBJECT_T18
extern bool object_t18_check_dismntr(void);
#endif

#ifdef MPTT_BUS_MONITOR
extern void mptt_bus_monitor_ticks(uint8_t tick);
#endif

/*============================================================================
void touch_timer_handler(void)
------------------------------------------------------------------------------
Purpose: This function updates the time elapsed to the touch key module to
         synchronize the internal time counts used by the module.
Input  : none
Output : none
Notes  :
============================================================================*/
void touch_timer_handler(void)
{
#ifdef OBJECT_T25
  if (TEST(qlib_touch_state, QTLIB_STATE_SUSPEND)) {
    return;
  }
  object_t25_cycling_ticks((uint8_t)measurement_period_store);
#endif

  // Update bit heart to bus monitor
#ifdef MPTT_BUS_MONITOR
#ifdef OBJECT_T18
  if (!object_t18_check_dismntr())
#endif
    mptt_bus_monitor_ticks((uint8_t)measurement_period_store);
#endif
  
  /* Count complete - Measure touch sensors */
  /* USE_MPTT_WRAPPER */
  // time_to_measure_touch_flag = 1u;
  SET(qlib_touch_state, QTLIB_STATE_TIME_TO_MEASURE);
  
#if (DEF_TOUCH_LOWPOWER_ENABLE == 1u)
  if (TEST(qlib_touch_state, QTLIB_STATE_SLEEP)) {
#ifdef DEF_TOUCH_LOWPOWER_SOFT
    // For software drift, we need record last drift time, and do measurement if timeout
    if (measurement_period_idle_drift) {
      time_since_last_drift += measurement_period_store;
      if (time_since_last_drift > measurement_period_idle_drift * 200) {
        time_since_last_drift = 0;
        SET(qlib_touch_state, QTLIB_STATE_SLEEP_WALK);
      }
    }
#else
    SET(qlib_touch_state, QTLIB_STATE_SLEEP_WALK);
#endif
  } 
#endif
  // For active to idle status, we need record last touch time
  if (time_since_touch < (65535u - measurement_period_store)) {
    time_since_touch += measurement_period_store;
  } else {
    time_since_touch = 65535;
  }
  tslib_key_sensors_update_timer(measurement_period_store);
}


/*============================================================================
USE_MPTT_WRAPPER
void touch_suspend(uint8_t suspend)
------------------------------------------------------------------------------
Purpose: Set a suspend flag that prevent library process scanning
Input  : None zero, enter suspend; otherwise exit suspend
Output : None
Notes  :
============================================================================*/
void touch_suspend(uint8_t suspend)
{
  if (suspend) {
    SET(qlib_touch_state, QTLIB_STATE_SUSPEND);
  } else {
    CLR(qlib_touch_state, QTLIB_STATE_SUSPEND);
  }
}

/*============================================================================
USE_MPTT_WRAPPER
void touch_inject_event(void)
------------------------------------------------------------------------------
Purpose: Set a external flag that library could process parameter changed
Input  : None
Output : None
Notes  :
============================================================================*/
void touch_inject_event(void)
{
  SET(qlib_touch_state, QTLIB_STATE_EXTERNAL_EVENT);
}

/*============================================================================
USE_MPTT_WRAPPER
int8_t touch_state_idle(void)
------------------------------------------------------------------------------
Purpose: Indicate whether the touch is in idle mode
Input  : none
Output : Zero Idle, Other Busy
Notes  :
============================================================================*/
int8_t touch_state_idle(void) 
{
  if (TEST(qlib_touch_state, QTLIB_STATE_ACTIVE) /* || TEST(qlib_touch_state, QTLIB_STATE_TIME_TO_MEASURE)*/) {
    return -1;
  }
  
  return 0;
}

/*============================================================================
USE_MPTT_WRAPPER
int8_t touch_state_sleep(void)
------------------------------------------------------------------------------
Purpose: Indicate whether the touch is in sleep mode
Input  : none
Output : Zero Sleep, Other none sleep
Notes  :
============================================================================*/
int8_t touch_state_sleep(void) 
{
#if (DEF_TOUCH_LOWPOWER_ENABLE == 1u)
  if (TEST(qlib_touch_state, QTLIB_STATE_SLEEP)) {
    return 0;
  }
#endif  
  return -1;
}

/*============================================================================
void touch_calibrate(void)
------------------------------------------------------------------------------
Purpose: Mark the calibration flag of touch processing
Input  : none
Output : none
Notes  :
============================================================================*/
void touch_calibrate(void)
{
  SET_BIT(qlib_measurement_state, MEASUREMENT_CAL_REQ);
}

/*============================================================================
void touch_init_sensor(void)
------------------------------------------------------------------------------
Purpose: Mark the sensor init flag of touch processing
Input  : none
Output : none
Notes  :
============================================================================*/
void touch_init_sensor(void)
{
  SET_BIT(qlib_measurement_state, MEASUREMENT_INIT_SENSOR_REQ);
}

/*============================================================================
void ISR_ADC0_RESRDY_vect(void)
------------------------------------------------------------------------------
Purpose:  Interrupt handler for ADC / PTC EOC Interrupt
Input    :  none
Output  :  none
Notes    :  none
============================================================================*/
void ISR_ADC0_RESRDY_vect(void)
{
#ifdef OBJECT_T25
  if (TEST(qlib_touch_state, QTLIB_STATE_SUSPEND))
    return;
#endif

  qtm_avr_da_ptc_handler_eoc();
}

#if (DEF_TOUCH_LOWPOWER_ENABLE == 1u)
#ifndef DEF_TOUCH_LOWPOWER_SOFT
/*============================================================================
void ISR_ADC0_WCOMP_vect(void)
------------------------------------------------------------------------------
Purpose:  Interrupt handler for ADC / PTC WCOMP Interrupt
Input    :  none
Output  :  none
Notes    :  none
============================================================================*/
void ISR_ADC0_WCOMP_vect(void)
{
#ifdef OBJECT_T25
  if (TEST(qlib_touch_state, QTLIB_STATE_SUSPEND))
    return;
#endif
  tslib_adc_handler_wcomp();
}
#endif
#endif

#endif /* TOUCH_C */
